// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamsSoup.Data;

namespace SamsSoup.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200824115831_AddedShoppingCartItems")]
    partial class AddedShoppingCartItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SamsSoup.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescription = "Clear Soups based on broths",
                            CategoryName = "Clear Soups"
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescription = "Soups made with cream",
                            CategoryName = "Cream Soups"
                        },
                        new
                        {
                            Id = 3,
                            CategoryDescription = "Soups made with chicken",
                            CategoryName = "Chicken Soups"
                        });
                });

            modelBuilder.Entity("SamsSoup.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoupId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("SamsSoup.Models.Soup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSoupOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Soups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsSoupOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.",
                            Price = 10m,
                            ShortDescription = "Lorem Ipsum",
                            SoupName = "Vegetable Clear Soup"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            IsSoupOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.",
                            Price = 15m,
                            ShortDescription = "Lorem Ipsum",
                            SoupName = "Mushroom Soup"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            IsSoupOfTheWeek = false,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.",
                            Price = 12m,
                            ShortDescription = "Lorem Ipsum",
                            SoupName = "Chicken and Chard Pasta Fagioli"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsSoupOfTheWeek = true,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.",
                            Price = 12m,
                            ShortDescription = "Lorem Ipsum",
                            SoupName = "Japanese Soup"
                        });
                });

            modelBuilder.Entity("SamsSoup.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("SamsSoup.Models.Soup", "Soup")
                        .WithMany()
                        .HasForeignKey("SoupId");
                });

            modelBuilder.Entity("SamsSoup.Models.Soup", b =>
                {
                    b.HasOne("SamsSoup.Models.Category", "Category")
                        .WithMany("Soups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
